### PR TITLE
Update slider

### PR DESCRIPTION
**Pull request by carolinepar**

### CODE REVIEW

**Review by Jaega — COMMENTED** [review]
I notice that when clicking the right icon for the first time, it will directly jump to the end. Is that abnormal?

**Comment by carolinepar** [comment]
> I notice that when clicking the right icon for the first time, it will directly jump to the end. Is that abnormal?

That definitely shouldn't be happening, I'll take a look

**Review by liruochen1998 — APPROVED** [review]
LGTM!

**Review by Jaega — APPROVED** [review]
Great!

**Pull request merged**
