### PR TITLE
Hotfix together sync

### PR DESCRIPTION
**Pull request by liruochen1998**
#51

### CODE REVIEW

**Review by carolinepar — APPROVED** [review]
Idk how to test togetherJS using localhost so I can't demo it but the code looks good! Nice job!!!

**Comment by liruochen1998** [comment]
Thanks, @carolinepar !  but if you are curious, even though it is localhost, you can still get the sharable link and test as if it is hosted!

**Comment by carolinepar** [comment]
> Thanks, @carolinepar ! but if you are curious, even though it is localhost, you can still get the sharable link and test as if it is hosted!

Oh that's awesome! Okay thanks for letting me know!

**Comment by carolinepar** [comment]
Okay I've demod it and it looks great! Thanks Larry!

**Review by Jaega — APPROVED** [review]
Looks good! Thanks Larry!

**Pull request merged**
